apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: web-app
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: mail-app
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: http
      protocol: TCP
      name: mail-app
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: Service
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
