apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: detector-app
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: http
  selector:
    app: detector-app