apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: web-app
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: mail-app
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: html
      protocol: TCP
      name: mail-app
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq
  selector:
    app: rabbitmq
