name: Test, build and release
on: [push]
jobs:
  static-test:
    name: Static test
    runs-on: ubuntu-latest
    steps:
      - name: Install splint
        run: |
          sudo apt install splint
      - name: Testing
        run: |
          splint --compdef --exportlocal main.c
  building-and-delivery:
    name: Build and delivery
    permissions:
      contents: write
    needs: [static-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_KEY }}

      - name: Build Docker image
        run: cd ./app1 && docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
