name: Test, build and release
on: [push]
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
jobs:
#  static-test:
#    name: Static test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install splint
#        run: |
#          sudo apt install splint
#      - name: Testing
#        run: |
#          splint --compdef --exportlocal main.c
  building-and-delivery:
    name: Build and delivery
    permissions:
      contents: write
#    needs: [static-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      - name: Build Docker image web-app
        run: cd ./web_app && docker build -t gulya99/fhszl-hf:web-app-${{ github.sha }} .
      - name: Push Docker image web-app
        run: docker push gulya99/fhszl-hf:web-app-${{ github.sha }}
      - name: Build Docker image mail-app
        run: cd ./mail_app && docker build -t gulya99/fhszl-hf:mail-app-${{ github.sha }} .
      - name: Push Docker image mail-app
        run: docker push gulya99/fhszl-hf:mail-app-${{ github.sha }}
      - name: Build Docker image redis
        run: cd ./redis && docker build -t gulya99/fhszl-hf:redis-${{ github.sha }} .
      - name: Push Docker image redis
        run: docker push gulya99/fhszl-hf:redis-${{ github.sha }}
      - name: asd
        run: docker run --restart always --name mail \
              -e RELAY_HOST=smtp.fhszlhf.com \
              -e RELAY_PORT=587 \
              -e RELAY_USERNAME=eh9jtc@fhszlhf.com \
              -e RELAY_PASSWORD=secretpassword \
              -d bytemark/smtp
      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
